Repository transparency-dev/tessera, pull requests merged in 2024-12, with the labels that each got.

#348 Instructions to launch a test instance from a VM
  cmd/conformance/README.md
  deployment/live/aws/codelab/README.md
  deployment/live/aws/codelab/terragrunt.hcl
  deployment/modules/aws/codelab/main.tf
  deployment/modules/aws/codelab/outputs.tf
  deployment/modules/aws/codelab/variables.tf
  deployment/modules/aws/storage/main.tf
  deployment/modules/aws/storage/outputs.tf
Labels: documentation, enhancement

#352 Reorganize codelab
  README.md
  cmd/conformance/README.md
  cmd/conformance/mysql/README.md
  cmd/conformance/posix/README.md
Labels: documentation

#344 [MySQL] Separate integration from publishing checkpoints
  cmd/conformance/mysql/main.go
  storage/mysql/mysql.go
  storage/mysql/mysql_test.go
  storage/mysql/schema.sql
Labels: enhancement

#365 improve the AWS codelab
  deployment/live/aws/codelab/README.md
Labels: documentation

#370 AWS CI pipeline
  .github/workflows/aws_integration_test.yml
  deployment/live/aws/conformance/ci/terragrunt.hcl
  deployment/live/aws/conformance/terragrunt.hcl
  deployment/modules/aws/conformance/main.tf
  deployment/modules/aws/conformance/outputs.tf
  deployment/modules/aws/conformance/variables.tf
Labels: enhancement

#383 Fix GCP 'bring up a personality' link
  cmd/conformance/README.md
Labels: documentation

#385 AWS Design doc.
  storage/aws/README.md
Labels: documentation

#380 Align AWS conformance deployment documentation with GCP's
  deployment/live/aws/conformance/README.md
  deployment/live/aws/conformance/ci/README.md
Labels: documentation

#391 Update storage design docs to include the publish step
  storage/aws/README.md
  storage/gcp/README.md
  storage/mysql/DESIGN.md
Labels: documentation

#428 Open AWS storage to being used with non-AWS MySQL and S3 services
  cmd/conformance/aws/main.go
  storage/aws/README.md
  storage/aws/aws.go
Labels: enhancement
